checkin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('auth/', include('checkin_auth.urls')),
    path('vistors/', include('vistors.urls'))
]

checkin_auth/urls.py
from django.conf.urls import url
from . import views

app_name = 'checkin_auth'

urlpatterns = [
    url(r'^login/$', views.login_user, name='login'),
    url(r'^logout/$', views.logout_user, name='logout'),
]

user_management/urls.py
from django.conf.urls import url
from . import views

app_name = 'user_management'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^user/register/$', views.create_user, name="register")
]

vistors/urls.py
from django.conf.urls import url
from . import views

app_name = 'vistors'

urlpatterns = [
    url(r'^create/$', views.register_entry, name='create'),
    url(r'^search/$', views.search_entry, name='search'),
    url(r'^search/add/$', views.search_to_add, name='search_to_add'),

]

user_management/models.py
from django.db import models

# Create your models here.

user_management/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from messages import messages
from django.db import IntegrityError
from vistors.models import Entry
from datetime import date
# Create your views here.


@login_required()
def home(request):
    """
            user dashboard
    """
    context = {}
    template_to_load = 'user_management/views/home/index.html'
    context['entries'] = Entry.objects.filter(time_stamp__date=date.today())
    return render(request, template_to_load, context)


@login_required()
def create_user(request):
    """
            creates new user
    """
    context = {}
    template_to_load = 'user_management/views/home/create_new_user.html'
    if request.method == "POST":
        try:
            user_data = {}
            user_data['first_name'] = request.POST['first']
            user_data['last_name'] = request.POST['last']
            user_data['username'] = request.POST['username']
            user_data['password'] = request.POST['password']
            user_data['is_staff'] = request.POST['admin']
            user_data['email'] = request.POST['email']
            user = User(**user_data)
            user.set_password(user_data['password'])
            user.save()
        except KeyError as e:
            context['message'] = str(e) + ' field is required'
        except IntegrityError as e:
            context['message'] = str(e)
        else:
            context['message'] = messages.USER_CREATED_SUCCESSFULLY
    return render(request, template_to_load, context)

user_management/templates/user_management/partials/header.html
{% load static %}
<header class="topbar" data-navbarbg="skin6">
    <nav class="navbar top-navbar navbar-expand-md">
        <div class="navbar-header" data-logobg="skin6">
            <!-- This is for the sidebar toggle which is visible on mobile only -->
            <a class="nav-toggler waves-effect waves-light d-block d-md-none" href="javascript:void(0)"><i
                    class="ti-menu ti-close"></i></a>
            <!-- ============================================================== -->
            <!-- Logo -->
            <!-- ============================================================== -->
            <div class="navbar-brand">
                <!-- Logo icon -->
                <a>
                    <b class="logo-icon">
                        <!-- Dark Logo icon -->
                        <img src="{% static 'user_management/assets/images/logo-icon.png'%}" alt="homepage" class="dark-logo" />
                        <!-- Light Logo icon -->
                        <img src="{% static 'user_management/assets/images/logo-icon.png'%}" alt="homepage" class="light-logo" />
                    </b>
                    <!--End Logo icon -->
                    <!-- Logo text -->
                    <span class="logo-text">
                        <!-- dark Logo text -->
                        <!-- <img src="{% static 'user_management/assets/images/Logo-DesignHub_whitebgg.jpg'%}" alt="homepage" class="dark-logo" /> -->
                        <!-- Light Logo text -->
                        <!-- <img src="{% static 'user_management/assets/images/Logo-DesignHub_whitebgg.jpg'%}" class="light-logo" alt="homepage" /> -->
                        <span>
                           Design Hub
                        </span>
                    </span>
                </a>
            </div>
            <!-- ============================================================== -->
            <!-- End Logo -->
            <!-- ============================================================== -->
            <!-- ============================================================== -->
            <!-- Toggle which is visible on mobile only -->
            <!-- ============================================================== -->
            <a class="topbartoggler d-block d-md-none waves-effect waves-light" href="javascript:void(0)"
                data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><i
                    class="ti-more"></i></a>
        </div>
        <!-- ============================================================== -->
        <!-- End Logo -->
        <!-- ============================================================== -->
        <div class="navbar-collapse collapse" id="navbarSupportedContent">
            <!-- ============================================================== -->
            <!-- toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-left mr-auto ml-3 pl-1">
                
            </ul>
            <!-- ============================================================== -->
            <!-- Right side toggle and nav items -->
            <!-- ============================================================== -->
            <ul class="navbar-nav float-right">
                <!-- ============================================================== -->
                <!-- Search -->
                <!-- ============================================================== -->
                
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:void(0)" data-toggle="dropdown"
                        aria-haspopup="true" aria-expanded="false">
                        <img src="{% static 'user_management/assets/images/users/profile-pic.jpg' %}" alt="user" class="rounded-circle"
                            width="40">
                        <span class="ml-2 d-none d-lg-inline-block"><span>Hello,</span> <span
                                class="text-dark">{{user.username}}</span> <i data-feather="chevron-down"
                                class="svg-icon"></i></span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right user-dd animated flipInY">
                        <form action="{% url 'checkin_auth:logout' %}" method="post">
                            {% csrf_token %}
                            <button class="dropdown-item" type="submit">
                                <i data-feather="power"
                                class="svg-icon mr-2 ml-1"></i>
                                Logout
                            </button>
                        </form>
                    </div>
                </li>
                <!-- ============================================================== -->
                <!-- User profile and search -->
                <!-- ============================================================== -->
            </ul>
        </div>
    </nav>
</header>

user_management/templates/user_management/partials/quick_actions_component.html
{% load static %}
<div class="col-md-6 col-lg-3">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Quick Actions</h4>
                        <div class="mt-4 activity">
                            <div class="d-flex align-items-start border-left-line pb-3">
                                <div>
                                    <a href="{% url 'vistors:create' %}" class="btn btn-info btn-circle mb-2 btn-item">
                                        <i data-feather="plus"></i>
                                    </a>
                                </div>
                                <div class="ml-3 mt-2">
                                    <h5 class="text-dark font-weight-medium mb-2"><a href="{% url 'vistors:create' %}">Record Visit Entry</a></h5>
                                    <p class="font-14 mb-2 text-muted">Register new entry <br> for a visitor or tenant
                                        
                                    </p>
                                </div>
                            </div>
                            <div class="d-flex align-items-start border-left-line pb-3">
                                <div>
                                    <a href="javascript:void(0)"
                                        class="btn btn-success btn-circle mb-2 btn-item" data-toggle="modal"
                                        data-target="#right-modal">
                                        <i data-feather="message-square"></i>
                                    </a>
                                </div>
                                <div class="ml-3 mt-2">
                                    <a class="text-dark font-weight-medium mb-2" data-toggle="modal"
                                        data-target="#right-modal">Quick Search</a>
                                    <p class="font-14 mb-2 text-muted">Search for an already registered visitor/tenant<br> visits
                                    </p>
                                </div>

                                <!-- Right modal content -->
                                <div id="right-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-md modal-right">
                                        <div class="modal-content">
                                            <div class="modal-header border-0">
                                                <span class="text-dark font-weight-medium">Quick Search Form</span>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-hidden="true">×</button>
                                            </div>
                                            <div class="modal-body">
                                                <form action="{% url 'vistors:search_to_add' %}" method="post">    
                                                     <div class="form-body">
                                                        {% csrf_token %}
                                                        <div class="form-group">
                                                            <div class="row">
                                                                <label class="col-lg-12 col-sm-12">Phone Number</label>
                                                                <div class="col-lg-12 col-sm-12">
                                                                    <div class="row">
                                                                        <div class="col-md-12 col-sm-12">
                                                                            <input type="text" name="phone" placeholder="Search by phone number" class="form-control" required>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-actions">
                                                        <div class="text-right">
                                                            <button type="submit" class="btn btn-info">Submit</button>
                                                            <button type="reset" class="btn btn-dark">Reset</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->

                            </div>
                            <div class="d-flex align-items-start border-left-line pb-3">
                                <div>
                                    <a href="javascript:void(0)"
                                        class="btn btn-danger btn-circle mb-2 btn-item" data-toggle="modal"
                                        data-target="#right-modal-detailed">
                                        <i data-feather="message-square"></i>
                                    </a>
                                </div>
                                <div class="ml-3 mt-2">
                                    <a class="text-dark font-weight-medium mb-2" data-toggle="modal"
                                        data-target="#right-modal-detailed">Entry Search</a>
                                    <p class="font-14 mb-2 text-muted">Detailed search for all registered <br> visits
                                    </p>
                                </div>

                                <!-- Right modal content -->
                                <div id="right-modal-detailed" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog modal-md modal-right">
                                        <div class="modal-content">
                                            <div class="modal-header border-0">
                                                <span class="text-dark font-weight-medium">Detailed Search Form</span>
                                                <button type="button" class="close" data-dismiss="modal"
                                                    aria-hidden="true">×</button>
                                            </div>
                                            <div class="modal-body">
                                                <form action="{% url 'vistors:search' %}" method="post">    
                                                     <div class="form-body">
                                                        {% csrf_token %}
                                                        <div class="form-group">
                                                            <div class="row">
                                                                <label class="col-lg-12 col-sm-12">Phone Number</label>
                                                                <div class="col-lg-12 col-sm-12">
                                                                    <div class="row">
                                                                        <div class="col-md-12 col-sm-12">
                                                                            <input type="text" name="phone" placeholder="Search by phone number" class="form-control">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="row">
                                                                <label class="col-lg-12 col-sm-12">Name</label>
                                                                <div class="col-lg-12 col-sm-12">
                                                                    <div class="row">
                                                                        <div class="col-md-12 col-sm-12">
                                                                            <input type="text" name="name" placeholder="Search by Name" class="form-control">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="row">
                                                                <label class="col-lg-12 col-sm-12">Temperature</label>
                                                                <div class="col-lg-12 col-sm-12">
                                                                    <div class="row">
                                                                        <div class="col-md-12 col-sm-12">
                                                                            <input type="text" name="temperature" placeholder="Search by temperature" class="form-control">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="row">
                                                                <label class="col-lg-12 col-sm-12">From Date</label>
                                                                <div class="col-lg-12 col-sm-12">
                                                                    <div class="row">
                                                                        <div class="col-md-12 col-sm-12">
                                                                            <input type="date" name="from_date" placeholder="Search by date" class="form-control">
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="form-actions">
                                                        <div class="text-right">
                                                            <button type="submit" class="btn btn-info">Submit</button>
                                                            <button type="reset" class="btn btn-dark">Reset</button>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div><!-- /.modal-content -->
                                    </div><!-- /.modal-dialog -->
                                </div><!-- /.modal -->

                            </div>
                            {% if user.is_staff %}
                                <div class="d-flex align-items-start border-left-line">
                                    <div>
                                        <a href="{% url 'user_management:register' %}" class="btn btn-cyan btn-circle mb-2 btn-item">
                                            <i data-feather="user"></i>
                                        </a>
                                    </div>
                                    
                                        <div class="ml-3 mt-2">
                                            <h5 class="text-dark font-weight-medium mb-2"> <a href="{% url 'user_management:register' %}">Register System User</a>
                                            </h5>
                                            <p class="font-14 mb-2 text-muted">Create a new user in <br> the system</p>
                                            
                                        </div>
                                    
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>

user_management/templates/user_management/partials/sidenavbar.html
<aside class="left-sidebar" data-sidebarbg="skin6">
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item"> <a href="{% url 'user_management:home' %}" class="sidebar-link"
                        aria-expanded="false"><i data-feather="home" class="feather-icon"></i><span
                            class="hide-menu">Dashboard</span></a></li>
                <li class="list-divider"></li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
</aside>